sonar.projectKey=mitchins_micropython-wifimanager
sonar.organization=mitchins
sonar.sources=wifi_manager
sonar.tests=.
sonar.inclusions=wifi_manager/**/*.py
sonar.test.inclusions=test/**,test_*.py
sonar.exclusions=micropython_unittest.py,test/network.py,test/logging.py,test/webrepl.py,wifi_manager_tests.py
sonar.coverage.exclusions=test/**,test_*.py,micropython_unittest.py,wifi_manager/setup.py,wifi_manager_tests.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest.xml
sonar.sourceEncoding=UTF-8
